apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2-v2
  labels:
    app: service2-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2-v2
        image: gcr.io/anthos-book-322415/service2:v2
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
