apiVersion: v1
kind: Service
metadata:
  name: service3
  labels:
    app: service3
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 9000
  - port: 443
    name: https
    protocol: TCP
    targetPort: 9000
  selector:
    app: service3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
  labels:
    app: service3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service3
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
      - name: service3
        image: gcr.io/anthos-book-322415/service3:latest
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: #IfNotPresent Always
        ports:
        - containerPort: 9000
